fail if there are missing tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -37,6 +37,15 @@ jobs:
       - name: Test step
         run: "deno test --allow-read --allow-net"
 
+      - name: Fail if there are any .ts or .tsx files in the project without a .test.ts or .test.tsx file
+        run: |
+            offenders=$(find . -name '*.ts' -o -name '*.tsx' | grep -v '\.test\.ts\?$')
+            if [ -n "$offenders" ]; then
+              echo "Error: The following .ts or .tsx files do not have a corresponding .test.ts or .test.tsx file:"
+              echo "$offenders"
+              exit 1
+            fi
+
       # - name: Upload to Deno Deploy
       #   uses: denoland/deployctl@v1
       #   with:
